export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  REFRESH_TOKENS_REQUEST: 'REFRESH_TOKENS_REQUEST',
  REFRESH_TOKENS_SUCCESS: 'REFRESH_TOKENS_SUCCESS',
  REFRESH_TOKENS_FAILURE: 'REFRESH_TOKENS_FAILURE',
};